config/routes.rb
Rails.application.routes.draw do

  root 'sessions#home'
  get '/home', to: 'sessions#home'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get   '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/history', to: 'sessions#history'
  post '/term', to: 'terms#create'
  get '/term', to: 'sessions#home'
  resources :users
  resources :terms

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/term.rb
class Term < ApplicationRecord
  belongs_to :user
  before_save { self.text = text.downcase }
  validates :text, presence: true, length: { maximum: 50 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :terms
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if logged_in?
      redirect_to root_path
    else
      render 'login'
     end
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      log_in @user
      redirect_to root_path
    else
      redirect_to login_path
    end
  end

  def destroy
    log_out
  end

  def history
    if logged_in?
    @res = current_user.terms
    else
      redirect_to action: "new"
    end
  end
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  include HTTParty

  def create
    if current_user.nil?
      redirect_to login_path and return
    end
    @term = current_user.terms.build(term_params)
    if @term.save
      @res = HTTParty.get("http://ws.audioscrobbler.com/2.0/?method=artist.getinfo&artist=#{@term.text}&api_key=1ca2cf614eeaa185c2b61753b434b599&format=json")
      render 'show'
    else
      redirect_to root_path
    end
  end
  
  private
    def term_params
      params.require(:term).permit(:text)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    if logged_in?
      redirect_to root_path and return
    end
    @user = User.new
  end

  def create
    @user = User.new(user_params)
  	if @user.save
  	  log_in @user
  	else
  	  render 'new' and return
    end
    redirect_to root_path
  end

   private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
    redirect_to login_path
  end
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/terms/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Artist Page</title>
	<link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>
<% if !logged_in? %>
<% redirect_to root %>
<% end %>
<section class="container4" style="height: 20px">
<div class="logout_button"><%= link_to "log out", logout_path, method: :delete%></div>
<div class="search_button"><%= link_to "search artist", root_path %></div>
</section>
<section class="container3">
<div class="left1"><img src=<%=@res["artist"]["image"][2]['#text']%> alt="image" ></div>
<div class="right1">
<div id="artist_name"><%= @res["artist"]["name"] %><br></div>
 mbid - <%= @res["artist"]["mbid"] %><br>
<a href=<%= @res["artist"]["url"] %>> see this artist on last fm </a><br>
<% if @res["artist"]["streamable"] %>
 streamable : yes <br>
<% else %>
 streamable : no <br><% end %>
<%= @res["artist"]["stats"]["listeners"]%> listeners<br>
<%= @res["artist"]["stats"]["playcount"]%> playcount<br>
</div>
</section>
 <section class="container4" style="height:auto"><div class="summary_title">summary</div> 
<p><%= @res["artist"]["bio"]["summary"]%></p></section>
<section class="container4"><div class="summary_title">Similar Artists</div><br><br>
<% @res["artist"]["similar"]["artist"].each do |similar| %>
   <div class="artist_grid">
   <div class="similar_artist_name"><%= similar["name"] %><br></div>
   <a href=<%= similar["url"] %>> see this artist on last fm </a><br>
   <div class="similar_artist_img"><img src=<%= similar["image"][1]['#text']%> alt="image" > </div>
   </div>
<% end %>
</section>
</body>
</html>

app/views/users/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
<head>
      <title>Sign Up Page</title>
      <link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>
      <div id="header">

<div id="header_text">
  Sign Up </div>
  </div>
  
  
<%= form_for(@user, url: signup_path) do |f| %>
<section class="container2">
  <%= render 'error_messages' %>
<div class="up">
      <div id="label1"><%= f.label :name %></div>
      <div id="input1"><%= f.text_field :name %></div>
</div></section><section class="container2">
<div class="up">
      <div id="label1"><%= f.label :email %></div>
      <div id="input1"><%= f.email_field :email %></div>
</div></section><section class="container2">
<div class="up">
      <div id="label1"><%= f.label :password %></div>
      <div id="input1"><%= f.password_field :password %></div>
</div></section><section class="container2">
<div class="up">
      <div id="label1"><%= f.label :password_confirmation, "Confirm Password" %></div>
      <div id="input1"><%= f.password_field :password_confirmation %></div>
</div></section><section class="container2">
<div class="center2">
      <%= f.submit "Create my account", class: "btn btn-primary" %>
      
</div></section>
<% end %>
</body>
</html>